### ISSUE TITLE
Restaurants missing

### ISSUE THREAD

**Issue by tuchfarber** [tuchfarber/Veto-It#3]
Pull more restaurants for a given area as many close restaurants are missing

**Comment by Harlantr** [comment]
Can we add a bar to show that the data is loading while we're grabbing the next "page" of locations?

**Comment by tuchfarber** [comment]
An option is the Radar API as it allows 200 results and should not involve the pagination delay: https://developers.google.com/maps/documentation/javascript/examples/place-radar-search. The downside is that it only returns a place_id, so to receive any useful information, we would need individual calls per id.

**Comment by tuchfarber** [comment]
Progress bar added in e36616e .

**Comment by tuchfarber** [comment]
Since 60 items is the hard limit from the API, we can't do much on this at the moment. We'll keep it in mind if we go with another API in the future.
