### ISSUE TITLE
Error Handling for Unresolved URLs

### ISSUE THREAD

**Issue by Harlantr** [tuchfarber/Veto-It#7]
When sharing a session, it is possible to change the session # in the URL to a nonsense number.  Doing this does not throw an error; it doesn't even update the map.

Updating the session ID in the URL should try to get data for that session ID from the database.  It should display an error to the user if no such data is available in the database.  It should also clear the current working state of the app, since the user is now in a fake session without real data.

**Comment by tuchfarber** [comment]
Backend is currently returning {"status":"Error", "status_text": "Document does not exist"} if it can't find the key in the DB. The changes can be triggered off of that response.
